# Generated by Django 4.2.2 on 2023-06-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tag_remove_profile_date_profile_created_at_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
