# Generated by Django 4.2.2 on 2023-06-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_follows_follows_unique_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='follower_user_id',
            new_name='follower_user',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_likes',
            old_name='user_id',
            new_name='user',
        ),
    ]
