# Generated by Django 4.2.2 on 2023-06-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_follower_user_id_follows_follower_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.comment'),
        ),
        migrations.AddField(
            model_name='user_likes',
            name='comment_likes',
            field=models.ManyToManyField(related_name='comments_liked', to='main_app.comment'),
        ),
        migrations.AddField(
            model_name='user_likes',
            name='post_likes',
            field=models.ManyToManyField(related_name='posts_liked', to='main_app.post'),
        ),
    ]
