# Generated by Django 4.2.2 on 2023-06-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_comment_profile_remove_post_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment_likes',
            field=models.ManyToManyField(related_name='comments_liked', to='main_app.comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_likes',
            field=models.ManyToManyField(related_name='posts_liked', to='main_app.post'),
        ),
        migrations.DeleteModel(
            name='User_likes',
        ),
    ]
