# Generated by Django 4.2.2 on 2023-06-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_follow_list_profile_follower_list_delete_follows_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            # name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
